[versions]
unstyled = "1.46.0"

kotlin = "2.2.20"
compose = "1.9.0"
agp = "8.6.1"
android-compileSdk = "35"
android-minSdk = "21"
hot-reload = "1.0.0-rc01"
nexusPublishPlugin = "2.0.0-rc-1"
activity-core = "1.10.1"
lucide = "1.0.0"
window = "1.4.0"

[libraries]
androidx-activitycompose = { module = "androidx.activity:activity-compose", version.ref = "activity-core" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
composables-icons-lucide = { module = "com.composables:icons-lucide", version.ref = "lucide" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hot-reload" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublishPlugin" }